name: amethystads
version: ${version}
main: net.jplayz.AmethystAdsPlugin
api-version: "1.15"
description: Map-ad plugin
author: amethystads
commands:
  amethystads:
    description: amethystADS admin commands
    usage: /amethystads <register|give|reload>
    permission: amethystads.admin
    aliases: [aa]
permissions:
  amethystads.admin:
    description: Admin commands (register, give ad tool, reload)
    default: op
